import Head from "next/head";
// Components
import Navbar from "@/components/Navbar";
import Banner from "@/components/Banner";
import MiniSlider from "@/components/MiniSlider";
import MegaBox from "@/components/MegaBox";
import BestSellerSlider from "@/components/BestSellerSlider";

export default function Home() {
  return (
    <>
      <Head>
        <title>Online Shoping UAE | Fashion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner />
      <MiniSlider />
      <MegaBox />
      <BestSellerSlider />
    </>
  );
}
